//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmploymentPayMVVMWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeHour
    {
        public int Emp_ { get; set; }
        public System.DateTime WorkDate { get; set; }
        public string Description { get; set; }
        public Nullable<int> HoursWorked { get; set; }
    
        public virtual EMPLOYEE EMPLOYEE { get; set; }
    }
}
